feat: styling updates to widget input step
Uniswap/widgets pull request #348
Opened 2023-01-03 23:57 UTC by just-toby

design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10575%3A115233&t=VFd894XSQCCzBYD0-4

updates sizings, spacings, and colors for the main widget root component, and the input/output fields. This PR focuses on the "input" step, which includes the initial view with and without tokens selected.
this also updates the colors in the theme to match the new design.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/66155195/210455366-7d235c71-6962-43a8-b713-562a3953c219.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/66155195/210455462-e5485a88-5c1e-41d3-9990-27cb24b88298.png">

2023-01-04 15:18 UTC, vm requested changes
I think widget uses `em` in particular for some reason?

2023-01-05 17:18 UTC, just-toby commented
@vm I think we should REM since we don't have a need to be scaling specific elements of the page separately. REM is a way to enforce consistent scaling throughout the entire page.

2023-01-05 20:12 UTC, just-toby commented
screenshot of the "wide" version:
<img width="323" alt="Screenshot 2023-01-05 at 12 11 47 PM" src="https://user-images.githubusercontent.com/66155195/210871284-136515ad-0bf0-45a8-b347-75581f76c805.png">

2023-01-06 19:46 UTC, vm approved these changes

2023-01-06 19:47 UTC, merged